name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  MONGO_URL: ${{ secrets.MONGO_URL }}
  PORT: ${{ secrets.PORT }}
  TEST_MONGO_URL: ${{ secrets.TEST_MONGO_URL }}
  SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start:test
          wait-on: http://localhost:3003
      - name: deploy
        if: ${{ github.event_name == 'push' && !(contains(join(toJson(github.event.commits.*.message)), '#skip')) }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "still-savannah-13643"
          heroku_email: "juhp944@gmail.com"
          healthcheck: "https://still-savannah-13643.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - name: failed build notification
        if: ${{ failure() && github.event_name == 'push' && !(contains(join(toJson(github.event.commits.*.message)), '#skip')) }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          description: ${{ github.event.commits[0].url }}
          text: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build success notification
        if: ${{ success() && github.event_name == 'push' && !(contains(join(toJson(github.event.commits.*.message)), '#skip')) }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: "https://still-savannah-13643.herokuapp.com"
          text: A new version of Bloglist has been deployed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !(contains(join(toJson(github.event.commits.*.message)), '#skip')) }}
        uses: anothrNick/github-tag-action@1.40.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true